# 공통의 설정을 정의한다
spring:
  profiles:
    # 디폴트를 명시적으로 지정한다
    # 로컬 환경 이외는 환경 변수로 프로파일을 전환한다
    default: local
    active: local
  messages:
    # 메시지 정의 파일의 경로를 포함하여 설정한다
    basename: messages,ValidationMessages,PropertyNames
    cache-duration: -1
    encoding: UTF-8
  jackson:
    # JSON의 키를 언더스코어 구분의 문자열로 한다
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      autoCommit: false
      connectionTimeout: 30000
      idleTimeout: 5000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      minimumIdle: 10
      maximumPoolSize: 30
  batch:
    initializer:
      # Job관리 테이블을 자동적으로 작성하지 않도록 한다.
      enabled: false
    job:
      # 자동적으로 배치 Job이 기동하지 않도록 한다
      enabled: false
doma:
  dialect: mysql
  # 소문자의 스네이크 케이스로 변환한다（firstName → first_name）
  naming: SNAKE_LOWER_CASE
  # SQL파일을 캐시한다
  sql-file-repository: greedy_cache
  # 벌크 인서트・업데이트의 사이즈
  batch-size: 1000
jmx:
  enabled: false
logging:
  pattern:
    # MDC에 설정한 값을 출력한다
    level: "[%X{BATCH_ID}] %5p"


####
# 애플리케이션의 설정
application:
  processFileLocation: build
